# Generated by Django 5.0.3 on 2024-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bids_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
