# Generated by Django 5.0.3 on 2024-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_siteuser_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
